### ISSUE TITLE
arm64 support

### ISSUE THREAD

**Issue by code-asher** [cdr/cloud-agent#11]
code-server issue: https://github.com/cdr/code-server/issues/2822

**Comment by oxy** [comment]
All that should be needed now is creating a release on GitHub, and the action should trigger and upload the binaries.
@jsjoeio can you create a v0.2.2?

**Comment by jsjoeio** [comment]
Sure! Let me try it

**Comment by jsjoeio** [comment]
Published! https://github.com/cdr/cloud-agent/releases/tag/v0.2.2

**Comment by jsjoeio** [comment]
Release running action: https://github.com/cdr/cloud-agent/actions/runs/800755286

**Comment by jsjoeio** [comment]
It worked! See assets: https://github.com/cdr/cloud-agent/releases/tag/v0.2.2
